micronaut:
  application:
    name: testContainers
  server:
    port: 8081
    context-path: /myapp  # Set your desired context path here
  router:
    static-resources:
      #http://localhost:8081/myapp/swagger-ui#/
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:15432/actor
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
